# Generated by Django 4.2.1 on 2023-05-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sancionatorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('expediente', models.CharField(max_length=255)),
                ('unidad_fiscalizable', models.CharField(max_length=255)),
                ('nombre_razon_social', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
    ]
